# Archivo de configuración para el entorno local de Supabase.

# Identificador del proyecto de Supabase en la nube.
project_id = "tufeojytxgbjjqjzlytv"

# Configuración de puertos para los servicios locales.
# Reasignados para evitar conflictos en entornos como GitHub Codespaces.
[api]
port = 8432
schemas = ["public", "storage", "graphql"]
max_rows = 1000

[db]
port = 8433
major_version = 17

[studio]
port = 8437

[inbucket]
port = 8436

# Configuración para el proveedor de autenticación de Google.
[auth.external.google]
enabled = true
# Las credenciales se cargan de forma segura desde variables de entorno.
# Asegúrate de que GOOGLE_CLIENT_ID y GOOGLE_CLIENT_SECRET estén en tu archivo .env.local.
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
# Requerido para que el flujo de autenticación de Google funcione en un entorno local.
skip_nonce_check = true

# Definición de las Edge Functions del proyecto.
[functions]
generate-narratives = {}
process-podcast-job = {}
queue-podcast-job = {}