# Para una referencia detallada de la configuraci칩n, visita:
# https://supabase.com/docs/guides/local-development/cli/config

project_id = "nicepods-platform"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

# NOTA: Las secciones [functions] y [edge_runtime] han sido eliminadas
# ya que no son necesarias para la configuraci칩n actual y estaban causando errores.
# La CLI utilizar치 su configuraci칩n por defecto, que es robusta.